### ISSUE TITLE
start does not match the corresponding path on disk `ActionTypes.js`

### ISSUE THREAD

**Issue by zanjs** [delvallejonatan/generator-create-redux-app#1]
## Failed to compile

./src/reducers/counter.js
Module not found: `project-name\src\constants\actionTypes.js` does not match the corresponding path on disk `ActionTypes.js`.

**Comment by delvallejonatan** [comment]
Let me take a closer look

**Comment by delvallejonatan** [comment]
Reinstall the generator `npm install -g generator-create-redux-app` I fixed in a new version.
